// In the Name of God, the Creative, the Originator
import type { CollectionConfig } from 'payload';

import { isAdmin } from '@/policies/isAdmin';
import { isLoggedIn } from '@/policies/isLoggedIn';
import { isReservationOwner } from '@/policies/isReservationOwner';
import {
  createReservationHandler,
  getReservationsHandler,
  getReceiptHandler,
} from '@/endpoints/reservations';

import { i18n } from '@/i18n';

export const Reservations: CollectionConfig = {
  slug: 'reservations',
  labels: i18n.collections.reservations.labels,
  // Custom endpoints at collection level to avoid conflict with /:id route
  endpoints: [
    {
      path: '/create',
      method: 'post',
      handler: createReservationHandler,
    },
    {
      path: '/list',
      method: 'get',
      handler: getReservationsHandler,
    },
    {
      path: '/receipt/:id',
      method: 'get',
      handler: getReceiptHandler,
    },
  ],
  admin: {
    group: i18n.collections.reservations.admin.group,
    useAsTitle: 'externalResId',
    defaultColumns: ['externalResId', 'pilgrim', 'status', 'bookedAt'],
  },
  access: {
    read: args => {
      if (isAdmin(args)) return true;
      return isReservationOwner(args);
    },
    create: isReservationOwner,
    update: args => {
      if (isAdmin(args)) return true;
      return isReservationOwner(args);
    },
    delete: args => {
      if (isAdmin(args)) return true;
      return isReservationOwner(args);
    },
  },
  fields: [
    {
      name: 'pilgrim',
      type: 'relationship',
      relationTo: 'pilgrims',
      required: true,
    },
    {
      name: 'externalResId',
      type: 'text',
      admin: {
        description: 'GUID generated by Atabat system',
      },
    },
    {
      name: 'tripSnapshot',
      type: 'json',
      required: true,
      admin: {
        description: 'Snapshot of trip details at the time of booking',
      },
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'pending',
      required: true,
      options: [
        { label: i18n.collections.reservations.fields.status.options.pending, value: 'pending' },
        {
          label: i18n.collections.reservations.fields.status.options.confirmed,
          value: 'confirmed',
        },
        { label: i18n.collections.reservations.fields.status.options.paid, value: 'paid' },
        {
          label: i18n.collections.reservations.fields.status.options.cancelled,
          value: 'cancelled',
        },
      ],
      label: i18n.collections.reservations.fields.status.label,
    },
    {
      name: 'paymentUrl',
      type: 'text',
    },
    {
      name: 'receiptData',
      type: 'json',
    },
    {
      name: 'costBreakdown',
      type: 'json',
    },
    {
      name: 'itinerary',
      type: 'json',
    },
    {
      name: 'bookedAt',
      type: 'date',
      defaultValue: () => new Date(),
    },
    {
      name: 'paidAt',
      type: 'date',
    },
  ],
};
